name: Docs
on:
  push:
  workflow_dispatch:
    inputs:
      skip-deploy:
        description: 'Skip deployment?'
        required: true
        type: boolean

permissions: {}

jobs:
  html:
    uses: named-data/actions/.github/workflows/docs-html.yml@v1
    with:
      # Deploy the 'new' branch as 'latest'
      deploy: ${{ !inputs.skip-deploy && github.ref == 'refs/heads/new' }}
      project: NAC
      version: latest
    secrets: inherit
