name: Docs
on:
  push:
    paths-ignore:
      - '*.md'
      - '.mailmap'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      JOB_NAME: Docs
      WAF_JOBS: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          case ${RUNNER_OS} in
            Linux) export NODE_LABELS="Linux Ubuntu" ;;
            macOS) export NODE_LABELS="OSX" ;;
          esac
          find .jenkins.d/ -type f -name '[1-9]*.sh' -exec chmod -x '{}' +
          ./.jenkins
      - name: Build documentation
        run: |
          ./waf --color=yes configure
          ./waf --color=yes build --targets=version.hpp
          ./waf --color=yes docs
